name: Build and Deploy Docker Image to EC2

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: SSH into EC2 and update Docker container
      uses: appleboy/ssh-action@master
      with:
        debug: true
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          # Debugging output
          echo "Connecting to EC2..."

          # Ensure SSH host key verification works
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.EC2_HOST }} > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

          # Ensure Docker is installed
          if ! command -v docker &> /dev/null; then
            echo "Docker not found. Installing..."
            sudo apt update && sudo apt install -y docker.io
            sudo systemctl start docker
            sudo systemctl enable docker
          else
            echo "Docker is already installed."
          fi

          # Debug Docker status
          sudo systemctl status docker || true

          # Pull new Docker images
          echo "Pulling Docker images..."
          sudo docker pull ${{ secrets.DOCKER_IMAGE_NAME_FRONTEND }}
          sudo docker pull ${{ secrets.DOCKER_IMAGE_NAME }}

          # Restart backend container
          echo "Restarting backend container..."
          sudo docker stop tracker-backend || true
          sudo docker rm tracker-backend || true
          sudo docker run -d --name tracker-backend -p 3000:3000 ${{ secrets.DOCKER_IMAGE_NAME }}

          # Restart frontend container
          echo "Restarting frontend container..."
          sudo docker stop tracker-frontend || true
          sudo docker rm tracker-frontend || true
          sudo docker run -d --name tracker-frontend -p 3001:3001 ${{ secrets.DOCKER_IMAGE_NAME_FRONTEND }}